### ISSUE TITLE
Support for Pirate audio

### ISSUE THREAD

**Issue by chemati8** [riban-bw/fluidbox#49]
Is it possible to use Pirate audio hat with drivers for ST7789 displays ?

**Comment by riban-bw** [comment]
I don't see why not. I must admit that this project was something I did for a specific purpose a few years ago and don't actually use it anymore. It uses the framebuffer for display so as long as the display can present as a framebuffer then GUI should work. (I can't think of many displays that would not.) And it uses alsa so a sound card that works should be okay.

I would be more concerned about its use of wiringPi which is no longer supported and won't work on a RPi5. It should work on RPi4 and earlier.
